# Generated by Django 6.0.3 on 2026-03-30 19:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_researcher_date_alter_researcher_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researcher',
            name='url',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='researcher',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
